/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module cmpleTest_23 (
    input clk,
    input rst,
    input button,
    input [3:0] count,
    output reg [15:0] out,
    output reg true,
    output reg [7:0] step
  );
  
  
  
  localparam START_state = 4'd0;
  localparam QQ1_state = 4'd1;
  localparam QQ2_state = 4'd2;
  localparam QQ3_state = 4'd3;
  localparam QQ4_state = 4'd4;
  localparam KK1_state = 4'd5;
  localparam KK2_state = 4'd6;
  localparam KK3_state = 4'd7;
  localparam KK4_state = 4'd8;
  localparam SUCCESS_state = 4'd9;
  localparam FAIL_state = 4'd10;
  
  reg [3:0] M_state_d, M_state_q = START_state;
  reg [27:0] M_timer_d, M_timer_q = 1'h0;
  wire [16-1:0] M_cmple_out;
  reg [16-1:0] M_cmple_a;
  reg [16-1:0] M_cmple_b;
  reg [6-1:0] M_cmple_alufn;
  sixteenbitcmp_7 cmple (
    .clk(clk),
    .rst(rst),
    .a(M_cmple_a),
    .b(M_cmple_b),
    .alufn(M_cmple_alufn),
    .out(M_cmple_out)
  );
  
  localparam QQ1A = 16'h6960;
  
  localparam QQ1B = 16'h696a;
  
  localparam QQ2A = 16'h696a;
  
  localparam QQ2B = 16'h6960;
  
  localparam QQ3A = 16'h696a;
  
  localparam QQ3B = 16'h696a;
  
  localparam QQ4A = 16'h7fff;
  
  localparam QQ4B = 16'h7fff;
  
  localparam KK1A = 16'h8a90;
  
  localparam KK1B = 16'h8a9c;
  
  localparam KK2A = 16'h8a9c;
  
  localparam KK2B = 16'h8a90;
  
  localparam KK3A = 16'h8a9c;
  
  localparam KK3B = 16'h8a9c;
  
  localparam KK4A = 16'h8000;
  
  localparam KK4B = 16'h8000;
  
  localparam QQ1 = 1'h1;
  
  localparam QQ2 = 1'h0;
  
  localparam QQ3 = 1'h1;
  
  localparam QQ4 = 1'h1;
  
  localparam KK1 = 1'h1;
  
  localparam KK2 = 1'h0;
  
  localparam KK3 = 1'h1;
  
  localparam KK4 = 1'h1;
  
  always @* begin
    M_state_d = M_state_q;
    M_timer_d = M_timer_q;
    
    out = 1'h0;
    M_cmple_a = 1'h0;
    M_cmple_b = 1'h0;
    M_timer_d = M_timer_q + 1'h1;
    M_cmple_alufn = 8'h37;
    true = 1'h0;
    step = 1'h0;
    
    case (M_state_q)
      START_state: begin
        if (count == 4'hc & button) begin
          M_timer_d = 1'h0;
          M_state_d = QQ1_state;
        end
      end
      QQ1_state: begin
        M_cmple_a = 16'h6960;
        M_cmple_b = 16'h696a;
        step = 1'h1;
        if (M_timer_q[26+1-:2] == 1'h0) begin
          out = 16'h6960;
        end else begin
          if (M_timer_q[26+1-:2] == 1'h1) begin
            out = 16'h696a;
          end else begin
            if (M_timer_q[26+1-:2] == 2'h2) begin
              out = M_cmple_out;
            end else begin
              if (M_timer_q[26+1-:2] == 2'h3) begin
                if (M_cmple_out == 1'h1) begin
                  M_timer_d = 1'h0;
                  M_state_d = QQ2_state;
                end else begin
                  M_state_d = FAIL_state;
                end
              end
            end
          end
        end
      end
      QQ2_state: begin
        M_cmple_a = 16'h696a;
        M_cmple_b = 16'h6960;
        step = 2'h2;
        if (M_timer_q[26+1-:2] == 1'h0) begin
          out = 16'h696a;
        end else begin
          if (M_timer_q[26+1-:2] == 1'h1) begin
            out = 16'h6960;
          end else begin
            if (M_timer_q[26+1-:2] == 2'h2) begin
              out = M_cmple_out;
            end else begin
              if (M_timer_q[26+1-:2] == 2'h3) begin
                if (M_cmple_out == 1'h0) begin
                  M_timer_d = 1'h0;
                  M_state_d = QQ3_state;
                end else begin
                  M_state_d = FAIL_state;
                end
              end
            end
          end
        end
      end
      QQ3_state: begin
        M_cmple_a = 16'h696a;
        M_cmple_b = 16'h696a;
        step = 3'h4;
        if (M_timer_q[26+1-:2] == 1'h0) begin
          out = 16'h696a;
        end else begin
          if (M_timer_q[26+1-:2] == 1'h1) begin
            out = 16'h696a;
          end else begin
            if (M_timer_q[26+1-:2] == 2'h2) begin
              out = M_cmple_out;
            end else begin
              if (M_timer_q[26+1-:2] == 2'h3) begin
                if (M_cmple_out == 1'h1) begin
                  M_timer_d = 1'h0;
                  M_state_d = QQ4_state;
                end else begin
                  M_state_d = FAIL_state;
                end
              end
            end
          end
        end
      end
      QQ4_state: begin
        M_cmple_a = 16'h7fff;
        M_cmple_b = 16'h7fff;
        step = 4'h8;
        if (M_timer_q[26+1-:2] == 1'h0) begin
          out = 16'h7fff;
        end else begin
          if (M_timer_q[26+1-:2] == 1'h1) begin
            out = 16'h7fff;
          end else begin
            if (M_timer_q[26+1-:2] == 2'h2) begin
              out = M_cmple_out;
            end else begin
              if (M_timer_q[26+1-:2] == 2'h3) begin
                if (M_cmple_out == 1'h1) begin
                  M_timer_d = 1'h0;
                  M_state_d = KK1_state;
                end else begin
                  M_state_d = FAIL_state;
                end
              end
            end
          end
        end
      end
      KK1_state: begin
        M_cmple_a = 16'h8a90;
        M_cmple_b = 16'h8a9c;
        step = 5'h10;
        if (M_timer_q[26+1-:2] == 1'h0) begin
          out = 16'h8a90;
        end else begin
          if (M_timer_q[26+1-:2] == 1'h1) begin
            out = 16'h8a9c;
          end else begin
            if (M_timer_q[26+1-:2] == 2'h2) begin
              out = M_cmple_out;
            end else begin
              if (M_timer_q[26+1-:2] == 2'h3) begin
                if (M_cmple_out == 1'h1) begin
                  M_timer_d = 1'h0;
                  M_state_d = KK2_state;
                end else begin
                  M_state_d = FAIL_state;
                end
              end
            end
          end
        end
      end
      KK2_state: begin
        M_cmple_a = 16'h8a9c;
        M_cmple_b = 16'h8a90;
        step = 6'h20;
        if (M_timer_q[26+1-:2] == 1'h0) begin
          out = 16'h8a9c;
        end else begin
          if (M_timer_q[26+1-:2] == 1'h1) begin
            out = 16'h8a90;
          end else begin
            if (M_timer_q[26+1-:2] == 2'h2) begin
              out = M_cmple_out;
            end else begin
              if (M_timer_q[26+1-:2] == 2'h3) begin
                if (M_cmple_out == 1'h0) begin
                  M_timer_d = 1'h0;
                  M_state_d = KK3_state;
                end else begin
                  M_state_d = FAIL_state;
                end
              end
            end
          end
        end
      end
      KK3_state: begin
        M_cmple_a = 16'h8a9c;
        M_cmple_b = 16'h8a9c;
        step = 7'h40;
        if (M_timer_q[26+1-:2] == 1'h0) begin
          out = 16'h8a9c;
        end else begin
          if (M_timer_q[26+1-:2] == 1'h1) begin
            out = 16'h8a9c;
          end else begin
            if (M_timer_q[26+1-:2] == 2'h2) begin
              out = M_cmple_out;
            end else begin
              if (M_timer_q[26+1-:2] == 2'h3) begin
                if (M_cmple_out == 1'h1) begin
                  M_timer_d = 1'h0;
                  M_state_d = KK4_state;
                end else begin
                  M_state_d = FAIL_state;
                end
              end
            end
          end
        end
      end
      KK4_state: begin
        M_cmple_a = 16'h8000;
        M_cmple_b = 16'h8000;
        step = 8'h80;
        if (M_timer_q[26+1-:2] == 1'h0) begin
          out = 16'h8000;
        end else begin
          if (M_timer_q[26+1-:2] == 1'h1) begin
            out = 16'h8000;
          end else begin
            if (M_timer_q[26+1-:2] == 2'h2) begin
              out = M_cmple_out;
            end else begin
              if (M_timer_q[26+1-:2] == 2'h3) begin
                if (M_cmple_out == 1'h1) begin
                  M_timer_d = 1'h0;
                  M_state_d = SUCCESS_state;
                end else begin
                  M_state_d = FAIL_state;
                end
              end
            end
          end
        end
      end
      SUCCESS_state: begin
        if (M_timer_q[27+0-:1] == 1'h1) begin
          true = 1'h1;
        end else begin
          if (M_timer_q[25+0-:1] == 1'h1) begin
            out = 16'hff00;
          end else begin
            if (M_timer_q[25+0-:1] == 1'h0) begin
              out = 16'h0000;
            end
          end
        end
      end
      FAIL_state: begin
        if (M_timer_q[25+0-:1] == 1'h1) begin
          out = 16'h00ff;
        end else begin
          out = 16'h0000;
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_timer_q <= 1'h0;
      M_state_q <= 1'h0;
    end else begin
      M_timer_q <= M_timer_d;
      M_state_q <= M_state_d;
    end
  end
  
endmodule
