/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module sixteen_bit_adder_6 (
    input clk,
    input rst,
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] sum,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] temp;
  
  always @* begin
    temp = 16'h0000;
    
    case (alufn[0+0-:1])
      1'h0: begin
        temp = a + b;
      end
      1'h1: begin
        temp = a - b;
      end
      default: begin
        temp = 16'h0000;
      end
    endcase
    v = (a[15+0-:1] & (b[15+0-:1] ^ alufn[0+0-:1]) & !temp[15+0-:1]) | (!a[15+0-:1] & !(b[15+0-:1] ^ alufn[0+0-:1]) & temp[15+0-:1]);
    z = ~(|temp);
    n = temp[15+0-:1];
    sum = temp;
  end
endmodule
