/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module sixteenbitcmp_7 (
    input clk,
    input rst,
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] out
  );
  
  
  
  reg [15:0] temp;
  
  always @* begin
    temp = 1'h0;
    
    case (alufn[1+1-:2])
      2'h1: begin
        temp = {15'h0000, (a == b)};
      end
      2'h2: begin
        temp = {15'h0000, (a < b)};
      end
      2'h3: begin
        temp = {15'h0000, (a <= b)};
      end
    endcase
    out = temp;
  end
endmodule
