/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module sixteenbitalu_3 (
    input clk,
    input rst,
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] out,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  wire [16-1:0] M_adder_sum;
  wire [1-1:0] M_adder_z;
  wire [1-1:0] M_adder_v;
  wire [1-1:0] M_adder_n;
  reg [16-1:0] M_adder_a;
  reg [16-1:0] M_adder_b;
  reg [6-1:0] M_adder_alufn;
  sixteen_bit_adder_6 adder (
    .clk(clk),
    .rst(rst),
    .a(M_adder_a),
    .b(M_adder_b),
    .alufn(M_adder_alufn),
    .sum(M_adder_sum),
    .z(M_adder_z),
    .v(M_adder_v),
    .n(M_adder_n)
  );
  wire [16-1:0] M_compare_out;
  reg [16-1:0] M_compare_a;
  reg [16-1:0] M_compare_b;
  reg [6-1:0] M_compare_alufn;
  sixteenbitcmp_7 compare (
    .clk(clk),
    .rst(rst),
    .a(M_compare_a),
    .b(M_compare_b),
    .alufn(M_compare_alufn),
    .out(M_compare_out)
  );
  wire [16-1:0] M_boolean_out;
  reg [16-1:0] M_boolean_a;
  reg [16-1:0] M_boolean_b;
  reg [6-1:0] M_boolean_alufn;
  sixteenbitbool_8 boolean (
    .clk(clk),
    .rst(rst),
    .a(M_boolean_a),
    .b(M_boolean_b),
    .alufn(M_boolean_alufn),
    .out(M_boolean_out)
  );
  wire [16-1:0] M_shifter_out;
  reg [16-1:0] M_shifter_a;
  reg [16-1:0] M_shifter_b;
  reg [6-1:0] M_shifter_alufn;
  sixteenbitshifter_9 shifter (
    .clk(clk),
    .rst(rst),
    .a(M_shifter_a),
    .b(M_shifter_b),
    .alufn(M_shifter_alufn),
    .out(M_shifter_out)
  );
  wire [16-1:0] M_multiplier_out;
  reg [16-1:0] M_multiplier_a;
  reg [16-1:0] M_multiplier_b;
  reg [6-1:0] M_multiplier_alufn;
  sixteenbitmul_10 multiplier (
    .clk(clk),
    .rst(rst),
    .a(M_multiplier_a),
    .b(M_multiplier_b),
    .alufn(M_multiplier_alufn),
    .out(M_multiplier_out)
  );
  
  always @* begin
    M_adder_alufn = alufn;
    M_adder_a = a;
    M_adder_b = b;
    z = M_adder_z;
    v = M_adder_v;
    n = M_adder_n;
    M_compare_alufn = alufn;
    M_compare_a = a;
    M_compare_b = b;
    M_boolean_alufn = alufn;
    M_boolean_a = a;
    M_boolean_b = b;
    M_shifter_alufn = alufn;
    M_shifter_a = a;
    M_shifter_b = b;
    M_multiplier_alufn = alufn;
    M_multiplier_a = a;
    M_multiplier_b = b;
    
    case (alufn[4+1-:2])
      2'h0: begin
        if (alufn[1+0-:1] == 1'h0) begin
          out = M_adder_sum;
        end else begin
          out = M_multiplier_out;
        end
      end
      2'h1: begin
        out = M_boolean_out;
      end
      2'h2: begin
        out = M_shifter_out;
      end
      2'h3: begin
        out = M_compare_out;
      end
    endcase
  end
endmodule
